import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageCode = "en" | "hi" | "mr" | "gu" | "ta" | "te";

export interface LanguageInfo {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
  region: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: "en", label: "English", nativeLabel: "English", region: "Official Operations" },
  { code: "hi", label: "Hindi", nativeLabel: "हिन्दी", region: "National Operational" },
  { code: "mr", label: "Marathi", nativeLabel: "मराठी", region: "West Coast Command" },
  { code: "gu", label: "Gujarati", nativeLabel: "ગુજરાતી", region: "North-West Sector" },
  { code: "ta", label: "Tamil", nativeLabel: "தமிழ்", region: "East Coast & Palk Strait" },
  { code: "te", label: "Telugu", nativeLabel: "తెలుగు", region: "Bay of Bengal Sector" },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Top Bar & Global
    "brand.name": "SAHAYYA",
    "brand.tagline": "Maritime Defense • Environmental Forensics • Intelligence",
    "brand.mdaOps": "MDA COMMAND",
    "brand.beta": "LIVE MDA",
    "brand.nationalMda": "NATIONAL MDA",
    "brand.config": "CONFIG",
    "brand.slogan": "Safer Oceans. Stronger Tomorrow.",
    "brand.subTitle": "Maritime Domain Awareness & Situational Grid",

    // Navigation
    "nav.home": "Home",
    "nav.map": "Map",
    "nav.incidents": "Incidents",
    "nav.vessels": "Vessels",
    "nav.analysis": "Analysis",
    "nav.authority": "Submit to Authority",
    "nav.settings": "Settings",
    "nav.help": "Help",
    "nav.backToDashboard": "Back to Dashboard",
    "nav.profileInfo": "Profile Information",
    "nav.signOut": "Sign Out",

    // Common Actions & Badges
    "action.search": "Search vessel (IMO, name), location or coordinates...",
    "action.save": "Save Changes",
    "action.saveProfile": "Save Profile Changes",
    "action.cancel": "Cancel",
    "action.downloadPdf": "Download PDF",
    "action.viewPdf": "View / Print PDF",
    "action.generateReport": "Generate Report",
    "action.generateAnalysisReport": "Generate Analysis Report",
    "action.reset": "Reset Defaults",
    "action.resetBaseline": "Reset Baseline",
    "action.resync": "Force Resync",
    "action.invite": "Invite Officer",
    "action.sendInvite": "Dispatch Official Invite",
    "action.signIn": "Sign In / Authenticate",
    "action.createAccount": "Create Account",
    "action.changePhoto": "Change Photo",
    "action.removePhoto": "Remove",
    "action.uploadNew": "Upload New Photo",
    "action.testPing": "Test Ping",
    "action.simulateAlert": "Simulate Test Alert",
    "action.compiling": "Compiling PDF...",
    "action.saving": "Saving...",
    "action.uploading": "Uploading...",

    // Status Badges & Telemetry
    "status.operational": "Systems Operational",
    "status.liveIncident": "Live Incident",
    "status.activeVessels": "Active Vessels",
    "status.connected": "Connected",
    "status.syncing": "Syncing",
    "status.active": "Active",
    "status.pending": "Pending",
    "status.verified": "Verified",
    "status.critical": "CRITICAL",
    "status.high": "HIGH",
    "status.medium": "MEDIUM",
    "status.low": "LOW",
    "status.restricted": "RESTRICTED",
    "status.admissible": "Court Admissible (MARPOL Annex I)",

    // Dashboard Overview
    "dash.incidentOverview": "Incident Command Overview",
    "dash.slickArea": "Oil Slick Extent",
    "dash.estVolume": "Estimated Discharge Volume",
    "dash.driftSpeed": "Net Drift Velocity",
    "dash.timeToLandfall": "Projected Shore Landfall ETA",
    "dash.primeSuspect": "Prime Suspect Attribution",
    "dash.attributionConfidence": "Attribution Confidence",
    "dash.weatherHeading": "Prevailing Sea State & Wind",
    "dash.quickSuggestions": "Quick Suggestions",
    "dash.recentActivity": "Recent Operational Event Audit Trail",
    "dash.satelliteDetection": "Satellite SAR Acquisition Profile",
    "dash.candidateVessels": "Candidate Vessel Priority Dossier",

    // Incident Stages
    "stage.ingestion": "1. SAR Ingestion & Satellite Pass",
    "stage.dna": "2. Spill DNA & Morphology Profile",
    "stage.drift": "3. Lagrangian Hydrodynamic Drift",
    "stage.attribution": "4. Suspect Vessel Attribution",
    "stage.response": "5. NOS-DCP Tactical Response",
    "stage.report": "6. Cryptographic Evidence Report",

    // Analysis Workstation
    "analysis.title": "Forensic Attribution & Scenario Lab",
    "analysis.subtitle": "Flowchart Stages 11, 12, 18 • Probabilistic vessel attribution and Lagrangian hydrodynamic modeling.",
    "analysis.tabs.counterfactual": "Oil Spill Origin & Forensic Lab",
    "analysis.tabs.whatif": "What-If Simulator",
    "analysis.tabs.confidence": "Model Confidence",
    "analysis.tabs.historical": "Historical Benchmarking",
    "analysis.tabs.reports": "Executive Reports",
    "analysis.whatIfTitle": "What-If Hydrodynamic Dispersion Simulator",
    "analysis.matrixTitle": "Model Confidence & Suspect Attribution Matrix",
    "analysis.traceabilityTitle": "Evidence Traceability & Chain of Custody",
    "analysis.historicalTitle": "Historical Analogue Benchmarking",

    // Settings Page
    "settings.title": "Settings & Tactical Administration",
    "settings.subtitle": "Configure operational officer credentials, automated response alert pipelines, sensor streams, and security policies.",
    "settings.profileTab": "Profile & Identity",
    "settings.notificationsTab": "Alert Pipelines",
    "settings.datasourcesTab": "Sensors & Telemetry",
    "settings.securityTab": "Security & Audit Vault",
    "settings.usersTab": "User Governance",
    "settings.accessibilityTab": "Locale & Ergonomics",
    "settings.officerProfile": "Officer Profile & Operational Credentials",
    "settings.fullName": "Full Name (Officer / Investigator)",
    "settings.govEmail": "Official Government / Service Email",
    "settings.organization": "Organization / Maritime Department",
    "settings.role": "Operational Role / Rank Designation",
    "settings.station": "Command Sector / Operations Station",
    "settings.callSign": "VHF Radio Call Sign / Code",
    "settings.digitalSig": "Courtroom Evidence Digital Signature Seal",
    "settings.digitalSigDesc": "Automatically stamp exported PDF dossiers with your digital identifier and SHA-256 verification seal.",
    "settings.alertChannels": "Operational Dispatch Channels",
    "settings.minSeverity": "Minimum Alert Trigger Threshold",
    "settings.stakeholderMatrix": "Stakeholder Auto-Notification Matrix",
    "settings.sensorFeeds": "Sensors & Real-Time Intelligence Ingestion",
    "settings.securityClearance": "Security Clearance & Cryptographic Evidence Vault",
    "settings.clearanceTier": "Clearance Tier",
    "settings.cryptoDigest": "Cryptographic Digest",
    "settings.twoFactor": "Two-Factor Auth (2FA)",
    "settings.sessionControls": "Operational Session Controls",
    "settings.autoLock": "Inactivity Auto-Lock Timeout",
    "settings.recentAudit": "Recent Command & Evidence Audit Log",
    "settings.userGovernance": "User & Access Governance (RBAC)",
    "settings.localeErgonomics": "Locale & Operational Ergonomics",
    "settings.primaryLang": "Command Center Primary Language",
    "settings.coordFormat": "GIS Coordinate Display Format",
    "settings.tacticalDisplay": "Tactical Display Controls",
    "settings.soundChime": "Audible Chime on Critical Discharge",
    "settings.highContrast": "High Contrast Bridge Screen Mode",
    "settings.largeText": "Enlarged Maritime Typography",
    "settings.reducedMotion": "Reduced Motion Mode",

    // Help Center
    "help.title": "Sahayya Help & Operations Center",
    "help.subtitle": "Official Maritime Intelligence, Hydrodynamic Simulation & Forensics Manual",
    "help.quickStart": "Quick Start Guide",
    "help.investigationGuide": "Incident Investigation Workflow",
    "help.moduleHelp": "Platform Modules Guide",
    "help.glossary": "Maritime Data Guide & Glossary",
    "help.troubleshooting": "Troubleshooting & Support",

    // Auth (Login/Register)
    "auth.welcomeBack": "Welcome Back",
    "auth.signInDesc": "Sign in to continue to Sahayya Command",
    "auth.createAccount": "Create Your Account",
    "auth.registerDesc": "Register to access Sahayya Maritime Intelligence",
    "auth.firstName": "Enter your First Name",
    "auth.email": "Enter your email address",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.haveAccount": "Already have an account?",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.agreeTerms": "I agree to the Maritime Data Security Regulations",
    "auth.heroTitle1": "Cleaner Oceans",
    "auth.heroTitle2": "for a Safer",
    "auth.heroTitle3": "Tomorrow",
    "auth.heroSubtitle": "From Satellite to Solution — Turning Ocean Data into Action.",
  },

  hi: {
    // Top Bar & Global
    "brand.name": "सहाय्य",
    "brand.tagline": "समुद्री सुरक्षा • पर्यावरण न्यायवैद्यक • आसूचना",
    "brand.mdaOps": "समुद्री कमान",
    "brand.beta": "सक्रिय निगरानी",
    "brand.nationalMda": "राष्ट्रीय समुद्री ग्रिड",
    "brand.config": "कॉन्फ़िगरेशन",
    "brand.slogan": "स्वच्छ महासागर। सुरक्षित कल।",
    "brand.subTitle": "राष्ट्रीय समुद्री क्षेत्र जागरूकता एवं स्थिति ग्रिड",

    // Navigation
    "nav.home": "मुख्यपृष्ठ",
    "nav.map": "नक्शा",
    "nav.incidents": "घटनाएँ",
    "nav.vessels": "जहाज",
    "nav.analysis": "विश्लेषण",
    "nav.authority": "प्राधिकरण को सौंपें",
    "nav.settings": "सेटिंग्स",
    "nav.help": "सहायता",
    "nav.backToDashboard": "डैशबोर्ड पर वापस",
    "nav.profileInfo": "प्रोफ़ाइल जानकारी",
    "nav.signOut": "लॉग आउट",

    // Common Actions & Badges
    "action.search": "जहाज (IMO, नाम), स्थान या निर्देशांक खोजें...",
    "action.save": "परिवर्तन सहेजें",
    "action.saveProfile": "प्रोफ़ाइल सहेजें",
    "action.cancel": "रद्द करें",
    "action.downloadPdf": "PDF डाउनलोड करें",
    "action.viewPdf": "PDF देखें / प्रिंट करें",
    "action.generateReport": "रिपोर्ट तैयार करें",
    "action.generateAnalysisReport": "विश्लेषण रिपोर्ट बनाएं",
    "action.reset": "डिफ़ॉल्ट रीसेट करें",
    "action.resetBaseline": "बेसलाइन रीसेट करें",
    "action.resync": "पुनः सिंक करें",
    "action.invite": "अधिकारी को आमंत्रित करें",
    "action.sendInvite": "आधिकारिक आमंत्रण भेजें",
    "action.signIn": "साइन इन / प्रमाणीकरण",
    "action.createAccount": "खाता बनाएं",
    "action.changePhoto": "फोटो बदलें",
    "action.removePhoto": "हटाएं",
    "action.uploadNew": "नई फोटो अपलोड करें",
    "action.testPing": "परीक्षण पिंग",
    "action.simulateAlert": "परीक्षण अलर्ट भेजें",
    "action.compiling": "PDF तैयार हो रहा है...",
    "action.saving": "सहेजा जा रहा है...",
    "action.uploading": "अपलोड हो रहा है...",

    // Status Badges & Telemetry
    "status.operational": "सिस्टम पूरी तरह सक्रिय",
    "status.liveIncident": "सक्रिय घटना",
    "status.activeVessels": "ट्रैक किए गए जहाज",
    "status.connected": "संबद्ध",
    "status.syncing": "सिंक हो रहा है",
    "status.active": "सक्रिय",
    "status.pending": "प्रतीक्षारत",
    "status.verified": "सत्यापित",
    "status.critical": "गंभीर",
    "status.high": "उच्च",
    "status.medium": "मध्यम",
    "status.low": "निम्न",
    "status.restricted": "गोपनीय",
    "status.admissible": "न्यायालय मान्य (MARPOL Annex I)",

    // Dashboard Overview
    "dash.incidentOverview": "घटना कमान सारांश",
    "dash.slickArea": "तेल फैलाव क्षेत्रफल",
    "dash.estVolume": "अनुमानित रिसाव मात्रा",
    "dash.driftSpeed": "बहाव गति",
    "dash.timeToLandfall": "तट पर पहुँचने का अनुमानित समय",
    "dash.primeSuspect": "प्रमुख संदिग्ध जहाज",
    "dash.attributionConfidence": "संदेह स्कोर",
    "dash.weatherHeading": "समुद्री स्थिति एवं हवा",
    "dash.quickSuggestions": "त्वरित सुझाव",
    "dash.recentActivity": "हालिया ऑपरेशनल ऑडिट ट्रेल",
    "dash.satelliteDetection": "उपग्रह रडार डिटेक्शन प्रोफ़ाइल",
    "dash.candidateVessels": "संदिग्ध जहाजों की प्राथमिकता सूची",

    // Incident Stages
    "stage.ingestion": "1. SAR रडार उपग्रह डेटा",
    "stage.dna": "2. तेल डीएनए एवं विस्तार प्रोफ़ाइल",
    "stage.drift": "3. जलगतिकीय बहाव सिमुलेशन",
    "stage.attribution": "4. संदिग्ध जहाज पहचान",
    "stage.response": "5. NOS-DCP त्वरित कार्रवाई",
    "stage.report": "6. प्रमाणित साक्ष्य रिपोर्ट",

    // Analysis Workstation
    "analysis.title": "फोरेंसिक पहचान एवं परिदृश्य प्रयोगशाला",
    "analysis.subtitle": "फ्लोचार्ट चरण 11, 12, 18 • संभावित पोत उत्तरदायित्व एवं लैग्रेंजियन हाइड्रोडायनामिक मॉडलिंग",
    "analysis.tabs.counterfactual": "काउंटरफैक्चुअल लैब",
    "analysis.tabs.whatif": "व्हाट-इफ सिम्युलेटर",
    "analysis.tabs.confidence": "मॉडल विश्वसनीयता",
    "analysis.tabs.historical": "ऐतिहासिक तुलना",
    "analysis.tabs.reports": "कार्यकारी रिपोर्ट",
    "analysis.whatIfTitle": "क्या-अगर जलगतिकीय सिमुलेटर",
    "analysis.matrixTitle": "मॉडल विश्वसनीयता एवं जहाज उत्तरदायित्व मैट्रिक्स",
    "analysis.traceabilityTitle": "साक्ष्य प्रमाणिकता एवं कस्टडी श्रृंखला",
    "analysis.historicalTitle": "ऐतिहासिक घटनाओं से तुलना",

    // Settings Page
    "settings.title": "सेटिंग्स एवं सामरिक प्रशासन",
    "settings.subtitle": "अधिकारी क्रेडेंशियल्स, स्वचालित अलर्ट पाइपलाइन, उपग्रह सेंसर एवं सुरक्षा नीतियां कॉन्फ़िगर करें।",
    "settings.profileTab": "प्रोफ़ाइल एवं पहचान",
    "settings.notificationsTab": "अलर्ट पाइपलाइन",
    "settings.datasourcesTab": "सेंसर एवं टेलीमेट्री",
    "settings.securityTab": "सुरक्षा एवं ऑडिट वॉल्ट",
    "settings.usersTab": "उपयोगकर्ता प्रशासन",
    "settings.accessibilityTab": "भाषा एवं संचालन नियंत्रण",
    "settings.officerProfile": "अधिकारी प्रोफ़ाइल एवं पहचान पत्र",
    "settings.fullName": "पूरा नाम (अधिकारी / अन्वेषक)",
    "settings.govEmail": "आधिकारिक सरकारी ईमेल",
    "settings.organization": "संगठन / समुद्री विभाग",
    "settings.role": "पद / परिचालन पदनाम",
    "settings.station": "कमान सेक्टर / स्टेशन",
    "settings.callSign": "VHF रेडियो कॉल साइन",
    "settings.digitalSig": "न्यायालय साक्ष्य डिजिटल हस्ताक्षर मुहर",
    "settings.digitalSigDesc": "डाउनलोड की जाने वाली रिपोर्टों पर डिजिटल हस्ताक्षर एवं SHA-256 सील स्वतः लगाएं।",
    "settings.alertChannels": "सक्रिय अलर्ट माध्यम",
    "settings.minSeverity": "न्यूनतम अलर्ट ट्रिगर स्तर",
    "settings.stakeholderMatrix": "हितधारक सूचना मैट्रिक्स",
    "settings.sensorFeeds": "उपग्रह सेंसर एवं डेटा स्रोत",
    "settings.securityClearance": "सुरक्षा स्तर एवं क्रिप्टोग्राफिक वॉल्ट",
    "settings.clearanceTier": "सुरक्षा क्लीयरेंस स्तर",
    "settings.cryptoDigest": "क्रिप्टोग्राफिक डाइजेस्ट",
    "settings.twoFactor": "द्वि-चरणीय प्रमाणीकरण (2FA)",
    "settings.sessionControls": "सत्र सुरक्षा नियंत्रण",
    "settings.autoLock": "स्वतः लॉक समय सीमा",
    "settings.recentAudit": "हालिया ऑपरेशनल सुरक्षा लॉग",
    "settings.userGovernance": "उपयोगकर्ता अधिकार प्रबंधन (RBAC)",
    "settings.localeErgonomics": "भाषा एवं डिस्प्ले नियंत्रण",
    "settings.primaryLang": "कमान केंद्र की प्राथमिक भाषा",
    "settings.coordFormat": "GIS निर्देशांक प्रारूप",
    "settings.tacticalDisplay": "सामरिक डिस्प्ले नियंत्रण",
    "settings.soundChime": "गंभीर रिसाव पर ध्वनि चेतावनी",
    "settings.highContrast": "उच्च कंट्रास्ट ब्रिज स्क्रीन मोड",
    "settings.largeText": "बड़ा समुद्री फ़ॉन्ट आकार",
    "settings.reducedMotion": "एनिमेशन कम करें",

    // Help Center
    "help.title": "सहाय्य सहायता एवं संचालन केंद्र",
    "help.subtitle": "आधिकारिक समुद्री आसूचना, जलगतिकीय सिमुलेशन एवं फोरेंसिक नियमावली",
    "help.quickStart": "त्वरित आरंभ गाइड",
    "help.investigationGuide": "घटना जांच कार्यप्रणाली",
    "help.moduleHelp": "प्लेटफ़ॉर्म मॉड्यूल गाइड",
    "help.glossary": "समुद्री शब्दावली एवं गाइड",
    "help.troubleshooting": "समस्या निवारण एवं सहायता",

    // Auth
    "auth.welcomeBack": "पुनः स्वागत है",
    "auth.signInDesc": "सहाय्य कमान केंद्र में प्रवेश करें",
    "auth.createAccount": "नया खाता बनाएं",
    "auth.registerDesc": "सहाय्य समुद्री आसूचना तक पहुंच के लिए पंजीकरण करें",
    "auth.firstName": "अपना पहला नाम दर्ज करें",
    "auth.email": "अपना ईमेल दर्ज करें",
    "auth.password": "पासवर्ड",
    "auth.confirmPassword": "पासवर्ड की पुष्टि करें",
    "auth.haveAccount": "पहले से खाता है?",
    "auth.dontHaveAccount": "खाता नहीं है?",
    "auth.agreeTerms": "मैं समुद्री डेटा सुरक्षा नियमों से सहमत हूँ",
    "auth.heroTitle1": "स्वच्छ महासागर",
    "auth.heroTitle2": "एक सुरक्षित",
    "auth.heroTitle3": "कल के लिए",
    "auth.heroSubtitle": "उपग्रह से समाधान तक — समुद्री डेटा को कार्रवाई में बदलना।",
  },

  mr: {
    // Top Bar & Global
    "brand.name": "सहाय्य",
    "brand.tagline": "सागरी संरक्षण • पर्यावरण न्यायवैद्यक • गुप्तवार्ता",
    "brand.mdaOps": "सागरी कमान",
    "brand.beta": "थेट देखरेख",
    "brand.nationalMda": "राष्ट्रीय सागरी ग्रीड",
    "brand.config": "कॉन्फिगरेशन",
    "brand.slogan": "स्वच्छ महासागर। सुरक्षित भविष्य।",
    "brand.subTitle": "राष्ट्रीय सागरी क्षेत्र जागरूकता आणि नियंत्रण ग्रीड",

    // Navigation
    "nav.home": "मुख्यपृष्ठ",
    "nav.map": "नकाशा",
    "nav.incidents": "घटना",
    "nav.vessels": "जहाजे",
    "nav.analysis": "विश्लेषण",
    "nav.authority": "प्राधिकरणास सादर करा",
    "nav.settings": "सेटिंग्ज",
    "nav.help": "मदत",
    "nav.backToDashboard": "डॅशबोर्डवर परत जा",
    "nav.profileInfo": "प्रोफाइल माहिती",
    "nav.signOut": "लॉग आउट",

    // Common Actions & Badges
    "action.search": "जहाज (IMO, नाव), स्थान किंवा निर्देशांक शोधा...",
    "action.save": "बदल जतन करा",
    "action.saveProfile": "प्रोफाइल जतन करा",
    "action.cancel": "रद्द करा",
    "action.downloadPdf": "PDF डाउनलोड करा",
    "action.viewPdf": "PDF पहा / प्रिंट करा",
    "action.generateReport": "अहवाल तयार करा",
    "action.generateAnalysisReport": "विश्लेषण अहवाल तयार करा",
    "action.reset": "रीसेट करा",
    "action.resetBaseline": "बेसलाइन रीसेट करा",
    "action.resync": "पुन्हा सिंक करा",
    "action.invite": "अधिकाऱ्यास आमंत्रित करा",
    "action.sendInvite": "अधिकृत आमंत्रण पाठवा",
    "action.signIn": "साइन इन / प्रमाणीकरण",
    "action.createAccount": "खाते तयार करा",
    "action.changePhoto": "फोटो बदला",
    "action.removePhoto": "काढून टाका",
    "action.uploadNew": "नवीन फोटो अपलोड करा",
    "action.testPing": "चाचणी पिंग",
    "action.simulateAlert": "चाचणी सूचना पाठवा",
    "action.compiling": "PDF संकलित होत आहे...",
    "action.saving": "जतन करत आहे...",
    "action.uploading": "अपलोड होत आहे...",

    // Status Badges & Telemetry
    "status.operational": "यंत्रणा पूर्णतः कार्यरत",
    "status.liveIncident": "सक्रिय घटना",
    "status.activeVessels": "ट्रॅक केलेली जहाजे",
    "status.connected": "जोडले आहे",
    "status.syncing": "सिंक होत आहे",
    "status.active": "सक्रिय",
    "status.pending": "प्रलंबित",
    "status.verified": "सत्यापित",
    "status.critical": "अतिगंभीर",
    "status.high": "उच्च",
    "status.medium": "मध्यम",
    "status.low": "कमी",
    "status.restricted": "गोपनीय",
    "status.admissible": "न्यायालयीन वैध (MARPOL Annex I)",

    // Dashboard Overview
    "dash.incidentOverview": "घटना कमान विहंगावलोकन",
    "dash.slickArea": "तेल गळती क्षेत्रफळ",
    "dash.estVolume": "अंदाजित गळती प्रमाण",
    "dash.driftSpeed": "प्रवाहाचा वेग",
    "dash.timeToLandfall": "किनाऱ्यावर पोहोचण्याचा अंदाजित वेळ",
    "dash.primeSuspect": "प्रमुख संशयित जहाज",
    "dash.attributionConfidence": "संशय गुण",
    "dash.weatherHeading": "सागरी स्थिती व वारे",
    "dash.quickSuggestions": "द्रुत सूचना",
    "dash.recentActivity": "अलीकडील कारवाई नोंदी",
    "dash.satelliteDetection": "उपग्रह रडार संपादन तपशील",
    "dash.candidateVessels": "संशयित जहाजांची प्राधान्य सूची",

    // Incident Stages
    "stage.ingestion": "१. SAR रडार उपग्रह डेटा",
    "stage.dna": "२. गळती डीएनए आणि स्वरूप",
    "stage.drift": "३. प्रवाह व दिशा मॉडेलिंग",
    "stage.attribution": "४. संशयित जहाज शोध",
    "stage.response": "५. NOS-DCP प्रतिसाद नियोजन",
    "stage.report": "६. प्रमाणित पुरावा अहवाल",

    // Analysis Workstation
    "analysis.title": "फॉरेन्सिक शोध आणि परिदृश्य प्रयोगशाळा",
    "analysis.subtitle": "फ्लोचार्ट टप्पे ११, १२, १८ • संभाव्य जहाज उत्तरदायित्व आणि लॅग्रेंजियन हायड्रोडायनामिक मॉडेलिंग",
    "analysis.tabs.counterfactual": "काउंटरफॅक्चुअल लॅब",
    "analysis.tabs.whatif": "व्हॉट-इफ सिम्युलेटर",
    "analysis.tabs.confidence": "मॉडेल विश्वासार्हता",
    "analysis.tabs.historical": "ऐतिहासिक तुलना",
    "analysis.tabs.reports": "कार्यकारी अहवाल",
    "analysis.whatIfTitle": "काय-जर सागरी प्रवाह सिम्युलेटर",
    "analysis.matrixTitle": "मॉडेल विश्वासार्हता आणि जबाबदारी तक्ता",
    "analysis.traceabilityTitle": "पुरावा सत्यता आणि साखळी",
    "analysis.historicalTitle": "ऐतिहासिक घटनांशी तुलना",

    // Settings Page
    "settings.title": "सेटिंग्ज आणि प्रशासकीय नियंत्रण",
    "settings.subtitle": "अधिकारी ओळख, स्वयंचलित सूचना प्रणाली, उपग्रह सेन्सर्स आणि सुरक्षा नियम कॉन्फिगर करा.",
    "settings.profileTab": "प्रोफाइल आणि ओळख",
    "settings.notificationsTab": "सूचना प्रणाली",
    "settings.datasourcesTab": "सेन्सर्स व टेलीमेट्री",
    "settings.securityTab": "सुरक्षा आणि ऑडिट तिजोरी",
    "settings.usersTab": "वापरकर्ता प्रशासन",
    "settings.accessibilityTab": "भाषा आणि नियंत्रण",
    "settings.officerProfile": "अधिकारी प्रोफाइल व ओळखपत्र",
    "settings.fullName": "पूर्ण नाव (अधिकारी / तपासनीस)",
    "settings.govEmail": "शासकीय / अधिकृत ईमेल",
    "settings.organization": "संस्था / सागरी विभाग",
    "settings.role": "पद / कार्य पदनाम",
    "settings.station": "कमान केंद्र / ठाणे",
    "settings.callSign": "VHF रेडिओ कॉल साइन",
    "settings.digitalSig": "न्यायालयीन पुरावा डिजिटल स्वाक्षरी शिक्का",
    "settings.digitalSigDesc": "डाउनलोड केलेल्या अहवालांवर डिजिटल स्वाक्षरी आणि SHA-256 सुरक्षा शिक्का स्वयंचलित लावा.",
    "settings.alertChannels": "सक्रिय सूचना माध्यमे",
    "settings.minSeverity": "किमान सूचना पातळी",
    "settings.stakeholderMatrix": "संबंधित संस्था सूचना तक्ता",
    "settings.sensorFeeds": "उपग्रह सेन्सर्स व डेटा प्रवाह",
    "settings.securityClearance": "सुरक्षा स्तर आणि एनक्रिप्शन",
    "settings.clearanceTier": "सुरक्षा मंजुरी स्तर",
    "settings.cryptoDigest": "क्रिप्टोग्राफिक डायजेस्ट",
    "settings.twoFactor": "दुहेरी प्रमाणीकरण (2FA)",
    "settings.sessionControls": "सत्र सुरक्षा नियंत्रणे",
    "settings.autoLock": "स्वयंचलित लॉक वेळ",
    "settings.recentAudit": "सुरक्षा तपासणी नोंदी",
    "settings.userGovernance": "वापरकर्ता अधिकार व्यवस्थापन (RBAC)",
    "settings.localeErgonomics": "भाषा व स्क्रीन नियंत्रणे",
    "settings.primaryLang": "कमान केंद्राची मुख्य भाषा",
    "settings.coordFormat": "GIS निर्देशांक स्वरूप",
    "settings.tacticalDisplay": "स्क्रीन प्रदर्शन नियंत्रणे",
    "settings.soundChime": "गंभीर गळतीवर ध्वनी चेतावणी",
    "settings.highContrast": "हाय कॉन्ट्रास्ट ब्रिज मोड",
    "settings.largeText": "मोठा सागरी फॉन्ट आकार",
    "settings.reducedMotion": "अ‍ॅनिमेशन कमी करा",

    // Help Center
    "help.title": "सहाय्य मदत आणि कार्य केंद्र",
    "help.subtitle": "अधिकृत सागरी गुप्तवार्ता, जलप्रवाह मॉडेलिंग आणि फॉरेन्सिक मार्गदर्शिका",
    "help.quickStart": "सुरुवात मार्गदर्शक",
    "help.investigationGuide": "घटना तपासणी कार्यपद्धती",
    "help.moduleHelp": "प्लॅटफॉर्म विभाग माहिती",
    "help.glossary": "सागरी संज्ञा आणि मार्गदर्शक",
    "help.troubleshooting": "समस्या निवारण आणि मदत",

    // Auth
    "auth.welcomeBack": "पुन्हा स्वागत आहे",
    "auth.signInDesc": "सहाय्य सागरी कमान केंद्रात प्रवेश करा",
    "auth.createAccount": "नवीन खाते तयार करा",
    "auth.registerDesc": "सहाय्य सागरी गुप्तवार्ता प्रणालीसाठी नोंदणी करा",
    "auth.firstName": "आपले पहिले नाव प्रविष्ट करा",
    "auth.email": "आपला ईमेल प्रविष्ट करा",
    "auth.password": "पासवर्ड",
    "auth.confirmPassword": "पासवर्ड पुष्टी करा",
    "auth.haveAccount": "आधीच खाते आहे?",
    "auth.dontHaveAccount": "खाते नाही?",
    "auth.agreeTerms": "मी सागरी डेटा सुरक्षा नियमांशी सहमत आहे",
    "auth.heroTitle1": "स्वच्छ महासागर",
    "auth.heroTitle2": "सुरक्षित",
    "auth.heroTitle3": "भविष्यासाठी",
    "auth.heroSubtitle": "उपग्रहापासून समाधानापर्यंत — सागरी डेटाचे कृतीत रूपांतर.",
  },

  gu: {
    // Top Bar & Global
    "brand.name": "સહાય્ય",
    "brand.tagline": "સમુદ્રી સુરક્ષા • પર્યાવરણીય ફોરેન્સિક્સ • ગુપ્તચર",
    "brand.mdaOps": "સમુદ્રી કમાન્ડ",
    "brand.beta": "લાઈવ નિરીક્ષણ",
    "brand.nationalMda": "રાષ્ટ્રીય સમુદ્રી ગ્રીડ",
    "brand.config": "રૂપરેખાંકન",
    "brand.slogan": "સ્વચ્છ સાગર. સુરક્ષિત આવતીકાલ.",
    "brand.subTitle": "રાષ્ટ્રીય સમુદ્રી ક્ષેત્ર જાગૃતિ અને સ્થિતિ ગ્રીડ",

    // Navigation
    "nav.home": "મુખ્યપૃષ્ઠ",
    "nav.map": "નકશો",
    "nav.incidents": "ઘટનાઓ",
    "nav.vessels": "જહાજો",
    "nav.analysis": "વિશ્લેષણ",
    "nav.authority": "સત્તામંડળને સબમિટ કરો",
    "nav.settings": "સેટિંગ્સ",
    "nav.help": "મદદ",
    "nav.backToDashboard": "ડેશબોર્ડ પર પાછા જાઓ",
    "nav.profileInfo": "પ્રોફાઇલ માહિતી",
    "nav.signOut": "લૉગ આઉટ",

    // Common Actions
    "action.search": "જહાજ (IMO, નામ), સ્થાન અથવા કોઓર્ડિનેટ્સ શોધો...",
    "action.save": "ફેરફારો સાચવો",
    "action.saveProfile": "પ્રોફાઇલ સાચવો",
    "action.cancel": "રદ કરો",
    "action.downloadPdf": "PDF ડાઉનલોડ કરો",
    "action.viewPdf": "PDF જુઓ / પ્રિન્ટ કરો",
    "action.generateReport": "અહેવાલ બનાવો",
    "action.generateAnalysisReport": "વિશ્લેષણ અહેવાલ બનાવો",
    "action.reset": "રીસેટ કરો",
    "action.resetBaseline": "બેઝલાઇન રીસેટ કરો",
    "action.resync": "ફરીથી સિંક કરો",
    "action.invite": "અધિકારીને આમંત્રણ આપો",
    "action.sendInvite": "સત્તાવાર આમંત્રણ મોકલો",
    "action.signIn": "સાઇન ઇન / પ્રમાણીકરણ",
    "action.createAccount": "ખાતું બનાવો",
    "action.changePhoto": "ફોટો બદલો",
    "action.removePhoto": "દૂર કરો",
    "action.uploadNew": "નવો ફોટો અપલોડ કરો",
    "action.testPing": "પિંગ પરીક્ષણ",
    "action.simulateAlert": "ચેતવણી પરીક્ષણ",
    "action.compiling": "PDF તૈયાર થઈ રહી છે...",
    "action.saving": "સાચવી રહ્યું છે...",
    "action.uploading": "અપલોડ થઈ રહ્યું છે...",

    // Status Badges
    "status.operational": "સિસ્ટમ સંપૂર્ણ સક્રિય",
    "status.liveIncident": "લાઈવ ઘટના",
    "status.activeVessels": "ટ્રેક કરેલા જહાજો",
    "status.connected": "જોડાયેલ",
    "status.syncing": "સિંક થઈ રહ્યું છે",
    "status.active": "સક્રિય",
    "status.pending": "બાકી",
    "status.verified": "ચકાસાયેલ",
    "status.critical": "ગંભીર",
    "status.high": "ઉચ્ચ",
    "status.medium": "મધ્યમ",
    "status.low": "ઓછું",
    "status.restricted": "ગોપનીય",
    "status.admissible": "કોર્ટ માન્ય (MARPOL Annex I)",

    // Dashboard Overview
    "dash.incidentOverview": "ઘટના કમાન્ડ વિહંગાવલોકન",
    "dash.slickArea": "તેલ ફેલાવો વિસ્તાર",
    "dash.estVolume": "અંદાજિત જથ્થો",
    "dash.driftSpeed": "પ્રવાહ ગતિ",
    "dash.timeToLandfall": "કિનારે પહોંચવાનો અંદાજિત સમય",
    "dash.primeSuspect": "મુખ્ય શંકાસ્પદ જહાજ",
    "dash.attributionConfidence": "શંકા સ્કોર",
    "dash.weatherHeading": "દરિયાઈ સ્થિતિ અને પવન",
    "dash.quickSuggestions": "ઝડપી સૂચનો",
    "dash.recentActivity": "તાજેતરની કામગીરી લોગ",
    "dash.satelliteDetection": "સેટેલાઇટ રડાર ડિટેક્શન પ્રોફાઇલ",
    "dash.candidateVessels": "શંકાસ્પદ જહાજોની યાદી",

    // Incident Stages
    "stage.ingestion": "૧. SAR રડાર સેટેલાઇટ ડેટા",
    "stage.dna": "૨. સ્પીલ ડીએનએ અને પ્રોફાઇલ",
    "stage.drift": "૩. પ્રવાહ સિમ્યુલેશન",
    "stage.attribution": "૪. શંકાસ્પદ જહાજ ઓળખ",
    "stage.response": "૫. NOS-DCP ઝડપી કાર્યવાહી",
    "stage.report": "૬. પ્રમાણિત પુરાવા અહેવાલ",

    // Settings
    "settings.title": "સેટિંગ્સ અને વહીવટી નિયંત્રણ",
    "settings.subtitle": "અધિકારી ઓળખ, ચેતવણી પાઇપલાઇન અને સેન્સર્સ રૂપરેખાંકિત કરો.",
    "settings.profileTab": "પ્રોફાઇલ અને ઓળખ",
    "settings.notificationsTab": "ચેતવણી પાઇપલાઇન",
    "settings.datasourcesTab": "સેન્સર્સ અને ટેલિમેટ્રી",
    "settings.securityTab": "સુરક્ષા અને ઓડિટ વૉલ્ટ",
    "settings.usersTab": "વપરાશકર્તા વ્યવસ્થાપન",
    "settings.accessibilityTab": "ભાષા અને નિયંત્રણો",
    "settings.officerProfile": "અધિકારી પ્રોફાઇલ અને ઓળખપત્ર",
    "settings.fullName": "પૂરું નામ",
    "settings.govEmail": "સત્તાવાર સરકારી ઇમેઇલ",
    "settings.organization": "સંસ્થા / વિભાગ",
    "settings.role": "હોદ્દો",
    "settings.station": "કમાન્ડ સ્ટેશન",
    "settings.callSign": "VHF કોલ સાઇન",
    "settings.digitalSig": "ડિજિટલ હસ્તાક્ષર સીલ",
    "settings.digitalSigDesc": "ડાઉનલોડ થતા અહેવાલો પર ડિજિટલ સહી અને SHA-256 સીલ આપમેળે લાગુ કરો.",
    "settings.primaryLang": "કમાન્ડ સેન્ટરની મુખ્ય ભાષા",
    "settings.coordFormat": "GIS કોઓર્ડિનેટ ફોર્મેટ",
    "settings.tacticalDisplay": "ડિસ્પ્લે નિયંત્રણો",
    "settings.soundChime": "ગંભીર ગળતી પર અવાજ ચેતવણી",
    "settings.highContrast": "હાઇ કોન્ટ્રાસ્ટ મોડ",
    "settings.largeText": "મોટા અક્ષરો",
    "settings.reducedMotion": "એનિમેશન ઓછું કરો",

    // Help
    "help.title": "સહાય્ય સહાય અને ઓપરેશન્સ કેન્દ્ર",
    "help.subtitle": "સત્તાવાર સમુદ્રી ગુપ્તચર અને ફોરેન્સિક માર્ગદર્શિકા",
    "help.quickStart": "ઝડપી શરૂઆત માર્ગદર્શિકા",
    "help.investigationGuide": "ઘટના તપાસ કાર્યપદ્ધતિ",
    "help.moduleHelp": "મોડ્યુલ માર્ગદર્શિકા",
    "help.glossary": "સમુદ્રી પરિભાષા",
    "help.troubleshooting": "મુશ્કેલીનિવારણ",

    // Auth
    "auth.welcomeBack": "ફરી સ્વાગત છે",
    "auth.signInDesc": "સહાય્ય કમાન્ડમાં પ્રવેશ કરો",
    "auth.createAccount": "નવું ખાતું બનાવો",
    "auth.registerDesc": "સહાય્ય સમુદ્રી ઇન્ટેલિજન્સ માટે નોંધણી કરો",
    "auth.firstName": "તમારું પ્રથમ નામ દાખલ કરો",
    "auth.email": "તમારો ઇમેઇલ દાખલ કરો",
    "auth.password": "પાસવર્ડ",
    "auth.confirmPassword": "પાસવર્ડની પુષ્ટિ કરો",
    "auth.haveAccount": "પહેલેથી ખાતું છે?",
    "auth.dontHaveAccount": "ખાતું નથી?",
    "auth.agreeTerms": "હું સમુદ્રી ડેટા સુરક્ષા નિયમો સાથે સંમત છું",
    "auth.heroTitle1": "સ્વચ્છ સાગર",
    "auth.heroTitle2": "સુરક્ષિત",
    "auth.heroTitle3": "આવતીકાલ માટે",
    "auth.heroSubtitle": "સેટેલાઇટથી ઉકેલ સુધી — સમુદ્રી ડેટાનું પગલાંમાં રૂપાંતર.",
  },

  ta: {
    // Top Bar & Global
    "brand.name": "சஹாய்யா",
    "brand.tagline": "கடல்சார் பாதுகாப்பு • சுற்றுச்சூழல் தடயவியல் • நுண்ணறிவு",
    "brand.mdaOps": "கடல்சார் கட்டளை",
    "brand.beta": "நேரலை கண்காணிப்பு",
    "brand.nationalMda": "தேசிய கடல்சார் கட்டமைப்பு",
    "brand.config": "அமைப்புகள்",
    "brand.slogan": "தூய்மையான பெருங்கடல்கள். பாதுகாப்பான எதிர்காலம்.",
    "brand.subTitle": "தேசிய கடல்சார் கள விழிப்புணர்வு மற்றும் நிலை கட்டமைப்பு",

    // Navigation
    "nav.home": "முகப்பு",
    "nav.map": "வரைபடம்",
    "nav.incidents": "சம்பவங்கள்",
    "nav.vessels": "கப்பல்கள்",
    "nav.analysis": "பகுப்பாய்வு",
    "nav.authority": "அதிகாரத்திடம் சமர்ப்பிக்கவும்",
    "nav.settings": "அமைப்புகள்",
    "nav.help": "உதவி",
    "nav.backToDashboard": "டாஷ்போர்டுக்கு திரும்பு",
    "nav.profileInfo": "சுயவிவர தகவல்",
    "nav.signOut": "வெளியேறு",

    // Common Actions
    "action.search": "கப்பல் (IMO, பெயர்), இடம் அல்லது ஆயங்களை தேடுக...",
    "action.save": "மாற்றங்களைச் சேமிக்கவும்",
    "action.saveProfile": "சுயவிவரத்தை சேமிக்கவும்",
    "action.cancel": "ரத்துசெய்",
    "action.downloadPdf": "PDF பதிவிறக்கவும்",
    "action.viewPdf": "PDF பார்க்க / அச்சிட",
    "action.generateReport": "அறிக்கை உருவாக்கவும்",
    "action.generateAnalysisReport": "பகுப்பாய்வு அறிக்கை உருவாக்கவும்",
    "action.reset": "மீட்டமை",
    "action.resetBaseline": "அடிப்படையை மீட்டமை",
    "action.resync": "மீண்டும் ஒத்திசைக்கவும்",
    "action.invite": "அதிகாரியை அழைக்கவும்",
    "action.sendInvite": "அழைப்பை அனுப்பவும்",
    "action.signIn": "உள்நுழைக",
    "action.createAccount": "கணக்கு உருவாக்கவும்",
    "action.changePhoto": "புகைப்படத்தை மாற்றவும்",
    "action.removePhoto": "நீக்கு",
    "action.uploadNew": "புதிய புகைப்படத்தைப் பதிவேற்றவும்",
    "action.testPing": "சோதனை பிங்",
    "action.simulateAlert": "சோதனை எச்சரிக்கை",
    "action.compiling": "PDF தொகுக்கப்படுகிறது...",
    "action.saving": "சேமிக்கப்படுகிறது...",
    "action.uploading": "பதிவேற்றப்படுகிறது...",

    // Status Badges
    "status.operational": "அமைப்புகள் செயல்படுகின்றன",
    "status.liveIncident": "நேரலை சம்பவம்",
    "status.activeVessels": "கண்காணிக்கப்படும் கப்பல்கள்",
    "status.connected": "இணைக்கப்பட்டது",
    "status.syncing": "ஒத்திசைக்கப்படுகிறது",
    "status.active": "செயலில்",
    "status.pending": "நிலுவையில்",
    "status.verified": "சரிபார்க்கப்பட்டது",
    "status.critical": "மிகவும் ஆபத்தானது",
    "status.high": "அதிகம்",
    "status.medium": "நடுத்தரமானது",
    "status.low": "குறைவு",
    "status.restricted": "ரகசியமானது",
    "status.admissible": "நீதிமன்ற ஏற்புடையது (MARPOL Annex I)",

    // Dashboard
    "dash.incidentOverview": "சம்பவ கட்டளை மேலோட்டம்",
    "dash.slickArea": "எண்ணெய் கசிவு பரப்பளவு",
    "dash.estVolume": "மதிப்பிடப்பட்ட கசிவு அளவு",
    "dash.driftSpeed": "நகர்வு வேகம்",
    "dash.timeToLandfall": "கரையை அடையும் கணிக்கப்பட்ட நேரம்",
    "dash.primeSuspect": "முதன்மை சந்தேக நபர் கப்பல்",
    "dash.attributionConfidence": "சந்தேக மதிப்பீடு",
    "dash.weatherHeading": "கடல் மற்றும் காற்று நிலை",
    "dash.quickSuggestions": "விரைவு பரிந்துரைகள்",
    "dash.recentActivity": "சமீபத்திய செயல்பாட்டு பதிவுகள்",
    "dash.satelliteDetection": "செயற்கைக்கோள் ரேடார் விவரக்குறிப்பு",
    "dash.candidateVessels": "சந்தேகத்திற்கிடமான கப்பல்கள்",

    // Stages
    "stage.ingestion": "1. SAR ரேடார் செயற்கைக்கோள் தரவு",
    "stage.dna": "2. கசிவு DNA மற்றும் விவரக்குறிப்பு",
    "stage.drift": "3. கடல்சார் நகர்வு மாதிரி",
    "stage.attribution": "4. சந்தேக கப்பல் அடையாளம்",
    "stage.response": "5. NOS-DCP விரைவு நடவடிக்கை",
    "stage.report": "6. சான்றளிக்கப்பட்ட அறிக்கை",

    // Settings
    "settings.title": "அமைப்புகள் மற்றும் நிர்வாகம்",
    "settings.subtitle": "அதிகாரி சுயவிவரம், எச்சரிக்கை அமைப்புகள் மற்றும் சென்சார்களை உள்ளமைக்கவும்.",
    "settings.profileTab": "சுயவிவரம் & அடையாளம்",
    "settings.notificationsTab": "எச்சரிக்கை அமைப்புகள்",
    "settings.datasourcesTab": "சென்சார்கள் & தரவு",
    "settings.securityTab": "பாதுகாப்பு பெட்டகம்",
    "settings.usersTab": "பயனர் மேலாண்மை",
    "settings.accessibilityTab": "மொழி & காட்சி கட்டுப்பாடு",
    "settings.officerProfile": "அதிகாரி சுயவிவரம்",
    "settings.fullName": "முழு பெயர்",
    "settings.govEmail": "அரசு மின்னஞ்சல்",
    "settings.organization": "துறை / அமைப்பு",
    "settings.role": "பணி நிலை",
    "settings.station": "கட்டளை தளம்",
    "settings.callSign": "VHF ரேடியோ அழைப்பு குறியீடு",
    "settings.digitalSig": "டிஜிட்டல் கையொப்ப முத்திரை",
    "settings.digitalSigDesc": "பதிவிறக்கும் அறிக்கைகளில் டிஜிட்டல் கையொப்பம் மற்றும் SHA-256 முத்திரையை தானாக இடுக.",
    "settings.primaryLang": "முதன்மை மொழி",
    "settings.coordFormat": "GIS ஆய வடிவமைப்பு",
    "settings.tacticalDisplay": "திரை காட்சி அமைப்புகள்",
    "settings.soundChime": "கசிவு எச்சரிக்கை ஒலி",
    "settings.highContrast": "உயர் மாறுபாடு பயன்முறை",
    "settings.largeText": "பெரிய எழுத்துக்கள்",
    "settings.reducedMotion": "அசைவுகளைக் குறைக்கவும்",

    // Help
    "help.title": "சஹாய்யா உதவி மையம்",
    "help.subtitle": "அதிகாரப்பூர்வ கடல்சார் நுண்ணறிவு மற்றும் தடயவியல் கையேடு",
    "help.quickStart": "விரைவு தொடக்க வழிகாட்டி",
    "help.investigationGuide": "சம்பவ விசாரணை வழிகாட்டி",
    "help.moduleHelp": "தொகுதி வழிகாட்டி",
    "help.glossary": "கடல்சார் கலைச்சொற்கள்",
    "help.troubleshooting": "சிக்கல் தீர்க்கும் உதவி",

    // Auth
    "auth.welcomeBack": "மீண்டும் வருக",
    "auth.signInDesc": "சஹாய்யா கட்டளை மையத்தில் நுழையவும்",
    "auth.createAccount": "புதிய கணக்கை உருவாக்கவும்",
    "auth.registerDesc": "சஹாய்யா அமைப்பில் பதிவு செய்யவும்",
    "auth.firstName": "முதல் பெயரை உள்ளிடவும்",
    "auth.email": "மின்னஞ்சலை உள்ளிடவும்",
    "auth.password": "கடவுச்சொல்",
    "auth.confirmPassword": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    "auth.haveAccount": "ஏற்கனவே கணக்கு உள்ளதா?",
    "auth.dontHaveAccount": "கணக்கு இல்லையா?",
    "auth.agreeTerms": "கடல்சார் தரவு பாதுகாப்பு விதிகளை ஏற்கிறேன்",
    "auth.heroTitle1": "தூய்மையான கடல்கள்",
    "auth.heroTitle2": "பாதுகாப்பான",
    "auth.heroTitle3": "நாளைக்காக",
    "auth.heroSubtitle": "செயற்கைக்கோளிலிருந்து தீர்வு வரை — கடல்சார் தரவை செயலாக மாற்றுதல்.",
  },

  te: {
    // Top Bar & Global
    "brand.name": "సహాయ్య",
    "brand.tagline": "సముద్ర రక్షణ • పర్యావరణ ఫోరెన్సిక్స్ • నిఘా",
    "brand.mdaOps": "సముద్ర కమాండ్",
    "brand.beta": "ప్రత్యక్ష పర్యవేక్షణ",
    "brand.nationalMda": "జాతీయ సముద్ర గ్రిడ్",
    "brand.config": "కాన్ఫిగరేషన్",
    "brand.slogan": "పరిశుభ్ర సముద్రాలు. సురక్షిత రేపు.",
    "brand.subTitle": "జాతీయ సముద్ర డొమైన్ అవగాహన మరియు కార్యాచరణ గ్రిడ్",

    // Navigation
    "nav.home": "హోమ్",
    "nav.map": "మ్యాప్",
    "nav.incidents": "సంఘటనలు",
    "nav.vessels": "నౌకలు",
    "nav.analysis": "విశ్లేషణ",
    "nav.authority": "అధికారానికి సమర్పించండి",
    "nav.settings": "సెట్టింగ్‌లు",
    "nav.help": "సహాయం",
    "nav.backToDashboard": "డ్యాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి",
    "nav.profileInfo": "ప్రొఫైల్ సమాచారం",
    "nav.signOut": "లాగ్ అవుట్",

    // Common Actions
    "action.search": "నౌక (IMO, పేరు), ప్రాంతం లేదా కోఆర్డినేట్లను శోధించండి...",
    "action.save": "మార్పులను సేవ్ చేయండి",
    "action.saveProfile": "ప్రొఫైల్ సేవ్ చేయండి",
    "action.cancel": "రద్దు చేయండి",
    "action.downloadPdf": "PDF డౌన్‌లోడ్ చేయండి",
    "action.viewPdf": "PDF చూడండి / ప్రింట్ చేయండి",
    "action.generateReport": "నివేదిక రూపొందించండి",
    "action.generateAnalysisReport": "విశ్లేషణ నివేదిక రూపొందించండి",
    "action.reset": "రీసెట్ చేయండి",
    "action.resetBaseline": "బేస్‌లైన్ రీసెట్ చేయండి",
    "action.resync": "మళ్ళీ సింక్ చేయండి",
    "action.invite": "అధికారిని ఆహ్వానించండి",
    "action.sendInvite": "ఆహ్వానం పంపండి",
    "action.signIn": "సైన్ ఇన్ / ప్రమాణీకరణ",
    "action.createAccount": "ఖాతా సృష్టించండి",
    "action.changePhoto": "ఫోటో మార్చండి",
    "action.removePhoto": "తొలగించండి",
    "action.uploadNew": "కొత్త ఫోటో అప్‌లోడ్ చేయండి",
    "action.testPing": "టెస్ట్ పింగ్",
    "action.simulateAlert": "హెచ్చరిక పరీక్ష",
    "action.compiling": "PDF సంకలనం చేయబడుతోంది...",
    "action.saving": "సేవ్ అవుతోంది...",
    "action.uploading": "అప్‌లోడ్ అవుతోంది...",

    // Status Badges
    "status.operational": "వ్యవస్థలు చురుగ్గా పనిచేస్తున్నాయి",
    "status.liveIncident": "ప్రత్యక్ష సంఘటన",
    "status.activeVessels": "ట్రాక్ చేయబడిన నౌకలు",
    "status.connected": "కనెక్ట్ చేయబడింది",
    "status.syncing": "సింక్ అవుతోంది",
    "status.active": "క్రియాశీల",
    "status.pending": "పెండింగ్",
    "status.verified": "ధృవీకరించబడింది",
    "status.critical": "తీవ్రమైన",
    "status.high": "అధిక",
    "status.medium": "మధ్యస్థ",
    "status.low": "తక్కువ",
    "status.restricted": "రహస్యమైనది",
    "status.admissible": "కోర్టు ఆమోదయోగ్యమైనది (MARPOL Annex I)",

    // Dashboard
    "dash.incidentOverview": "సంఘటన కమాండ్ అవలోకనం",
    "dash.slickArea": "చమురు విస్తీర్ణ ప్రాంతం",
    "dash.estVolume": "అంచనా వేసిన విడుదల పరిమాణం",
    "dash.driftSpeed": "ప్రవాహ వేగం",
    "dash.timeToLandfall": "తీరానికి చేరుకునే అంచనా సమయం",
    "dash.primeSuspect": "ప్రధాన అనుమానిత నౌక",
    "dash.attributionConfidence": "అనుమాన స్కోరు",
    "dash.weatherHeading": "సముద్ర మరియు గాలి స్థితి",
    "dash.quickSuggestions": "త్వరిత సూచనలు",
    "dash.recentActivity": "ఇటీవలి కార్యాచరణ లాగ్",
    "dash.satelliteDetection": "ఉపగ్రహ రాడార్ ప్రొఫైల్",
    "dash.candidateVessels": "అనుమానిత నౌకల జాబితా",

    // Stages
    "stage.ingestion": "1. SAR రాడార్ ఉపగ్రహ డేటా",
    "stage.dna": "2. స్పిల్ DNA మరియు ప్రొఫైల్",
    "stage.drift": "3. జల ప్రవాహ అనుకరణ",
    "stage.attribution": "4. అనుమానిత నౌక గుర్తింపు",
    "stage.response": "5. NOS-DCP ప్రతిస్పందన ప్రణాళిక",
    "stage.report": "6. ధృవీకరించబడిన సాక్ష్య నివేదిక",

    // Settings
    "settings.title": "సెట్టింగ్‌లు మరియు పరిపాలన",
    "settings.subtitle": "అధికారి ప్రొఫైల్, హెచ్చరిక పైప్‌లైన్లు మరియు సెన్సార్లను కాన్ఫిగర్ చేయండి.",
    "settings.profileTab": "ప్రొఫైల్ & గుర్తింపు",
    "settings.notificationsTab": "హెచ్చరిక వ్యవస్థ",
    "settings.datasourcesTab": "సెన్సార్లు & టెలిమెట్రీ",
    "settings.securityTab": "భద్రత మరియు ఆడిట్ వాల్ట్",
    "settings.usersTab": "వినియోగదారు నిర్వహణ",
    "settings.accessibilityTab": "భాష & నియంత్రణలు",
    "settings.officerProfile": "అధికారి ప్రొఫైల్",
    "settings.fullName": "పూర్తి పేరు",
    "settings.govEmail": "ప్రభుత్వ ఈమెయిల్",
    "settings.organization": "సంస్థ / సముద్ర విభాగం",
    "settings.role": "హోదా",
    "settings.station": "కమాండ్ స్టేషన్",
    "settings.callSign": "VHF కాల్ సైన్",
    "settings.digitalSig": "డిజిటల్ సంతకం ముద్ర",
    "settings.digitalSigDesc": "డౌన్‌లోడ్ చేసే నివేదికలపై డిజిటల్ సంతకం మరియు SHA-256 ముద్రను స్వయంచాలకంగా జోడించండి.",
    "settings.primaryLang": "కమాండ్ సెంటర్ ప్రధాన భాష",
    "settings.coordFormat": "GIS కోఆర్డినేట్ ఫార్మాట్",
    "settings.tacticalDisplay": "డిస్ప్లే నియంత్రణలు",
    "settings.soundChime": "తీవ్రమైన చమురు లీక్‌పై శబ్ద హెచ్చరిక",
    "settings.highContrast": "హై కాంట్రాస్ట్ మోడ్",
    "settings.largeText": "పెద్ద అక్షరాలు",
    "settings.reducedMotion": "యానిమేషన్‌లను తగ్గించండి",

    // Help
    "help.title": "సహాయ్య సహాయ కేంద్రం",
    "help.subtitle": "అధికారిక సముద్ర నిఘా మరియు ఫోరెన్సిక్స్ మాన్యువల్",
    "help.quickStart": "త్వరిత ప్రారంభ గైడ్",
    "help.investigationGuide": "సంఘటన విచారణ వర్క్‌ఫ్లో",
    "help.moduleHelp": "మాడ్యూల్ సమాచారం",
    "help.glossary": "సముద్ర పదకోశం",
    "help.troubleshooting": "సమస్య పరిష్కారం",

    // Auth
    "auth.welcomeBack": "తిరిగి స్వాగతం",
    "auth.signInDesc": "సహాయ్య కమాండ్ సెంటర్‌లోకి ప్రవేశించండి",
    "auth.createAccount": "కొత్త ఖాతాను సృష్టించండి",
    "auth.registerDesc": "సహాయ్య సముద్ర నిఘా వ్యవస్థకు నమోదు చేసుకోండి",
    "auth.firstName": "మీ మొదటి పేరును నమోదు చేయండి",
    "auth.email": "మీ ఈమెయిల్ నమోదు చేయండి",
    "auth.password": "పాస్‌వర్డ్",
    "auth.confirmPassword": "పాస్‌వర్డ్‌ను నిర్ధారించండి",
    "auth.haveAccount": "ఇప్పటికే ఖాతా ఉందా?",
    "auth.dontHaveAccount": "ఖాతా లేదా?",
    "auth.agreeTerms": "నేను సముద్ర డేటా భద్రతా నిబంధనలను అంగీకరిస్తున్నాను",
    "auth.heroTitle1": "పరిశుభ్ర సముద్రాలు",
    "auth.heroTitle2": "సురక్షితమైన",
    "auth.heroTitle3": "రేపటి కోసం",
    "auth.heroSubtitle": "ఉపగ్రహం నుండి పరిష్కారం వరకు — సముద్ర డేటాను చర్యగా మార్చడం.",
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
  supportedLanguages: LanguageInfo[];
  currentLanguageInfo: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem("sahayya_language") as LanguageCode;
    if (saved && TRANSLATIONS[saved]) {
      return saved;
    }
    return "en";
  });

  const setLanguage = (lang: LanguageCode) => {
    if (TRANSLATIONS[lang]) {
      setLanguageState(lang);
      localStorage.setItem("sahayya_language", lang);
    }
  };

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    if (TRANSLATIONS.en && TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    return fallback !== undefined ? fallback : key;
  };

  const currentLanguageInfo =
    SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        supportedLanguages: SUPPORTED_LANGUAGES,
        currentLanguageInfo,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
